MODEL:
  meta:
    arch: mnn_mlp
    cnn_type: ~
    mlp_type: mnn_mlp

  mnn_mlp:
    structure:
      - 784
      - 1000

    num_class: 10
    bn_bias_var: False
    predict_bias: True
    predict_bias_var: False
    special_init: True
    dropout: ~
    momentum: 0.9
    eps: 1.e-5

  snn_mlp:
   structure:
    - 784
    - 800
   num_class: 10
   use_cov: False
   bn_bias_var: False

CRITERION:
  name: CrossEntropyOnMean
  source: mnn_core
  args: 
   reduction: mean


OPTIMIZER:
  name: AdamW
  args:
    lr: 0.001
    weight_decay: 0.01


DATAAUG_TRAIN:
  aug_order:
    - ToTensor

  RandomCrop:
   size: 28
   padding: 2

DATAAUG_VAL:
  aug_order:
    - ToTensor

workers: 2
lr: 0.001
epochs: 30
bs: 50
pin_mem: True
world_size: 1
dataset: mnist
dataset_type: classic
input_prepare: flatten_poisson
save_epoch_state: False
scale_factor: 0.1
is_classify: True
background_noise: ~
dump_path: ./checkpoint/

